# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/USTC/COD_LAB_2021/lab5/COD_lab5/COD_lab5.srcs/sources_1/ip/InstrMem/InstrMem.xci
# IP: The module: 'InstrMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USTC/COD_LAB_2021/lab5/COD_lab5/COD_lab5.gen/sources_1/ip/InstrMem/InstrMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstrMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/USTC/COD_LAB_2021/lab5/COD_lab5/COD_lab5.srcs/sources_1/ip/InstrMem/InstrMem.xci
# IP: The module: 'InstrMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USTC/COD_LAB_2021/lab5/COD_lab5/COD_lab5.gen/sources_1/ip/InstrMem/InstrMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstrMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
