@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 19 22:47:46 +0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FIFO_sim_behav -key {Behavioral:sim_1:Functional:FIFO_sim} -tclbatch FIFO_sim.tcl -view D:/USTC/COD_LAB_2021/lab2/FIFO/regfile_sim_behav.wcfg -log simulate.log"
call xsim  FIFO_sim_behav -key {Behavioral:sim_1:Functional:FIFO_sim} -tclbatch FIFO_sim.tcl -view D:/USTC/COD_LAB_2021/lab2/FIFO/regfile_sim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
