# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/single_circle_xdc.xdc

# IP: ip/DataMem/DataMem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DataMem || ORIG_REF_NAME==DataMem} -quiet] -quiet

# IP: ip/InstrMem/InstrMem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==InstrMem || ORIG_REF_NAME==InstrMem} -quiet] -quiet
